# SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bs.SALES * b.PRICE) TOTAL_SALES

SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bs.SALES * b.PRICE) TOTAL_SALES

FROM AUTHOR a 
        LEFT JOIN BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
        LEFT JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
        
WHERE MONTH(bs.SALES_DATE) = 1

GROUP BY a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY

ORDER BY a.AUTHOR_ID, b.CATEGORY DESC