WITH RECURSIVE GENERATIONS AS (
    
    SELECT 
        ID, PARENT_ID, 1 AS GENERATION
    FROM
        ECOLI_DATA
    WHERE 
        PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        e.ID, e.PARENT_ID, g.GENERATION + 1 AS GENERATION
    FROM
        ECOLI_DATA e
        JOIN GENERATIONS g ON e.PARENT_ID = g.ID
)

SELECT ID

FROM GENERATIONS

WHERE GENERATION = 3

ORDER BY 1