WITH RECURSIVE G AS (

    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA e, G g
    WHERE e.PARENT_ID = g.ID
    
)

SELECT ID
FROM G
WHERE GENERATION = 3