WITH child_count AS (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)

SELECT 
    ID, IFNULL(CHILD_COUNT, 0) CHILD_COUNT

FROM 
    ECOLI_DATA ed
        LEFT JOIN child_count cc ON ed.ID = cc.PARENT_ID

ORDER BY
    ID