-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE * SUM(SALES_AMOUNT) SALES
FROM PRODUCT p
    LEFT JOIN OFFLINE_SALE os ON os.PRODUCT_ID = p.PRODUCT_ID  
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE

# SELECT SUM(sales_amount)
# FROM PRODUCT p
#     LEFT JOIN OFFLINE_SALE os ON os.PRODUCT_ID = p.PRODUCT_ID
# WHERE p.PRODUCT_CODE = 'D1000000'