SELECT
    c.CAR_ID, 
    c.CAR_TYPE, 
    ROUND(DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100, 0) FEE
    
FROM
    CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE LIKE '30%'
    
WHERE
    c.CAR_TYPE IN ('세단', 'SUV')
    AND
    C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE  START_DATE < '2022-12-01' AND '2022-11-01' <= END_DATE
    )
    AND
    ROUND(DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100, 0) BETWEEN 500000 AND 2000000

ORDER BY
    3 DESC, 2, 1 DESC
    
    