SELECT YEAR(os.SALES_DATE) YEAR, MONTH(os.SALES_DATE) MONTH, ui.GENDER GENDER, COUNT(DISTINCT os.USER_ID) USERS

FROM ONLINE_SALE os LEFT JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID

WHERE ui.GENDER IS NOT NULL

GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER

ORDER BY YEAR, MONTH, GENDER