

SELECT 
    YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH, 
    COUNT(DISTINCT s.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT s.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) PUCHASED_RATIO
 
FROM
    USER_INFO i
        JOIN ONLINE_SALE s ON i.USER_ID = s.USER_ID
 
WHERE YEAR(i.JOINED) = '2021'

GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE)
    
ORDER BY
    1, 2