WITH USER_COUNT AS (
    SELECT COUNT(*) COUNT
    FROM USER_INFO i
    WHERE YEAR(i.JOINED) = '2021'
)

SELECT
    YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH, 
    COUNT(DISTINCT i.USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT i.USER_ID) / c.COUNT, 1) AS PUCHASED_RATIO
    
FROM
    USER_COUNT c,
    USER_INFO i
        JOIN ONLINE_SALE s ON i.USER_ID = s.USER_ID
        
WHERE YEAR(i.JOINED) = '2021'

GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE)

ORDER BY
    1, 2