SELECT
    ID,
    CASE
        WHEN 1000 < SIZE_OF_COLONY THEN 'HIGH'
        WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
        WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        
    END AS SIZE

FROM
    ECOLI_DATA
    
ORDER BY 1