SELECT
    p.PRODUCT_ID, p.PRODUCT_NAME, SUM(PRICE * AMOUNT) TOTAL_SALES

FROM
    FOOD_PRODUCT p
        JOIN FOOD_ORDER o 
        ON p.PRODUCT_ID = o.PRODUCT_ID AND DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'

GROUP BY p.PRODUCT_ID

ORDER BY
    3 DESC, 1