WITH F AS (
    SELECT SUM(CODE) CODE FROM SKILLCODES WHERE CATEGORY='Front End'
)

SELECT
    ID, EMAIL, FIRST_NAME, LAST_NAME

FROM
    DEVELOPERS d, F f

WHERE
     f.CODE & d.SKILL_CODE
    
ORDER BY 1