WITH MAX AS (
        SELECT EMP_NO, SUM(SCORE) SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
        ORDER BY SCORE DESC
        LIMIT 1
    )

SELECT
    m.SCORE, m.EMP_NO, EMP_NAME, POSITION, EMAIL
    
FROM MAX m
        JOIN HR_EMPLOYEES e ON m.EMP_NO = e.EMP_NO
        JOIN HR_DEPARTMENT d ON e.DEPT_ID = d.DEPT_ID