SELECT
    CONCAT('/home/grep/src/', ugf.BOARD_ID, '/', ugf.FILE_ID, ugf.FILE_NAME, ugf.FILE_EXT) FILE_PATH

FROM USED_GOODS_FILE ugf, USED_GOODS_BOARD ugb

WHERE 
    ugb.VIEWS in (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
    AND ugf.BOARD_ID = ugb.BOARD_ID

ORDER BY FILE_ID DESC